# Generated by Django 5.0.6 on 2024-06-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_nuevo_proyecto_estudiante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuevo_proyecto',
            name='profesor',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
    ]
