# Generated by Django 5.0.6 on 2024-06-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_nuevo_proyecto_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuevo_proyecto',
            name='profesor',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
