# Generated by Django 5.0.6 on 2024-06-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuevo_proyecto',
            name='estudiante',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nuevo_proyecto',
            name='profesor',
            field=models.TextField(max_length=50),
        ),
    ]
